version: 2
updates:
  # Node.js依存関係の更新設定
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "npm"
      prefix-development: "npm dev"
      include: "scope"
    # セキュリティアップデートの優先設定
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "security"

  # GitHub Actions依存関係の更新設定
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
